name: Go
on:
  issue_comment:
    types:
      - created
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install npm
      run: npm install @octokit/action
    - uses: actions/checkout@v3
    
    - name: ADD PR NUMBER
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          const core = require('@actions/core')
          const { Octokit } = require("@octokit/action");
          let promise = await new Octokit().rest.actions.listJobsForWorkflowRun({
              owner: "yusuf-erdem",
              repo: "go-private-example",
              run_id: 3225359112,
              per_page: 100,
              page:1
          })


          await promise
          console.log(promise.data)
          const prNumber = context.payload.number;
          core.exportVariable('PULL_NUMBER_PAYLOAD', prNumber);
          console.log("Logger: " + prNumber)
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: print env
      run: |
          env
          cat /home/runner/work/_temp/_github_workflow/event.json
    - name: Test Go
      run: |
          go test -v -json ./... > ./test-report.json -coverprofile=coverage.out
    - name: ls files
      run: ls -l
    - name: ls files
      run: ls -l
    - name: Foresight Action
      if: success() || failure()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.F_LAB_API_KEY }}
        test_framework: golang
        test_format: json
        test_path: ./test-report.json
        coverage_format: golang
        coverage_path: |
            coverage.out
